### ISSUE TITLE
No pull-requests allowed?

### ISSUE THREAD

**Issue by strider72** [fny/calibre-Installer#5]
I tried to submit a pull-request with improvements I made (including calling the 64-bit version of calibre).  Github says I don't have "permission to access calibre-installer".

**Comment by fny** [comment]
Hmm... Not sure what's going on. Make sure to use the HTTPS URL.

Also sorry for the delay in replying! This repository fell off my radar since I've been running Linux primarily until recently.

**Comment by fny** [comment]
It's been a while. I'm closing this until I hear back again!
